# Generated by Django 3.2.7 on 2021-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subject_name',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='course_id',
            new_name='todoTitileid',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
