# Generated by Django 3.2.7 on 2021-09-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210913_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='todotitile',
            name='updated_at',
        ),
    ]
